language: node_js
node_js:
  - 15
script:
  - npm test
  - npm run coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - script: COVERALLS_FLAG_NAME=test-1 npm run coveralls
notifications:
  webhooks: https://coveralls.io/webhook
